version: '3'

services:
  coffeetalk-mongo-db:
    container_name: coffeetalk-mongo-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  coffeetalk-mongo-express:
    container_name: coffeetalk-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: coffeetalk-mongo-db
    depends_on:
      - coffeetalk-mongo-db

  coffeetalk-service-profile:
    container_name: coffeetalk-service-profile
    image: ctprofile:1.0
    build:
      context: ../
      dockerfile: profile/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - coffeetalk-mongo-db

  coffeetalk-service-matching:
    container_name: coffeetalk-service-matching
    image: ctmatching:1.0
    build: 
      context: ../
      dockerfile: matching/Dockerfile
    ports:
      - 5100:80
    depends_on: 
      - coffeetalk-mongo-db